# Generated by Django 5.1.1 on 2024-09-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_alter_refereelicence_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unavailability',
            options={'ordering': ['date_from', 'date_to'], 'verbose_name_plural': 'Unavailabilities'},
        ),
    ]
