# Generated by Django 5.1.1 on 2024-09-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0003_alter_unavailability_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='referee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='surname',
        ),
    ]
