# Generated by Django 5.1.1 on 2024-09-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0004_alter_referee_options_remove_referee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['profile__user__first_name']},
        ),
    ]
