# Generated by Django 5.1.1 on 2024-09-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0005_alter_referee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['profile__user__last_name']},
        ),
    ]
