# Generated by Django 5.1.1 on 2024-09-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0006_alter_referee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['licence__id', 'profile__user__last_name', 'profile__user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='refereelicence',
            options={'ordering': ['id']},
        ),
    ]
