# Generated by Django 5.1.1 on 2024-09-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_options_and_more'),
        ('referees', '0007_alter_referee_options_alter_refereelicence_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='licence',
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['licence_type__id', 'profile__user__last_name', 'profile__user__first_name']},
        ),
        migrations.AddField(
            model_name='referee',
            name='licence_number',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.CreateModel(
            name='RefereeLicenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AM', 'AM'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5)),
                ('competition_level', models.ManyToManyField(blank=True, related_name='licence_types', to='competitions.competitionlevel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='referee',
            name='licence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referees', to='referees.refereelicencetype'),
        ),
        migrations.DeleteModel(
            name='RefereeLicence',
        ),
    ]
