# Generated by Django 5.1.1 on 2024-10-15 14:16

import django.core.validators
import validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0009_alter_referee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='licence_number',
            field=models.IntegerField(default=None, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='referee',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[validators.validators.validate_rating]),
        ),
    ]
