# Generated by Django 5.1.1 on 2024-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_team_phone'),
        ('referees', '0010_alter_referee_licence_number_alter_referee_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refereelicencetype',
            name='competition_level',
        ),
        migrations.AddField(
            model_name='refereelicencetype',
            name='competition_levels',
            field=models.ManyToManyField(blank=True, related_name='referee_licence_types', to='competitions.competitionlevel'),
        ),
    ]
