# Generated by Django 5.1.1 on 2024-09-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('referees', '0003_alter_unavailability_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereferee',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='referees.referee'),
        ),
    ]
