# Generated by Django 5.1.1 on 2024-10-09 11:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilereferee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemanager',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None),
        ),
    ]
