# Generated by Django 5.1.1 on 2024-10-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilemanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemanager',
            name='manager_type',
            field=models.CharField(blank=True, choices=[('Referee Manager', 'Referee Manager'), ('Delegation Manager', 'Delegation Manager'), ('Competition Manager', 'Competition Manager'), ('Site Manager', 'Site Manager')], max_length=20, null=True),
        ),
    ]
