# Generated by Django 5.1.1 on 2024-09-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Extraliga muži', 'Extraliga muži'), ('Extraliga ženy', 'Extraliga ženy'), ('1. liga muži', '1. liga muži'), ('1. liga ženy', '1. liga ženy'), ('1. liga juniori', '1. liga juniori'), ('1. liga juniorky', '1. liga juniorky'), ('Kadeti západ', 'Kadeti západ'), ('Kadetky západ', 'Kadetky západ')], max_length=64, unique=True)),
                ('category', models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women'), ('junior boys', 'junior boys'), ('junior girls', 'junior girls'), ('cadet boys', 'cadet boys'), ('cadet girls', 'cadet girls')], max_length=64, null=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('extra_league', 'extra_league'), ('first_league', 'first_league'), ('regional', 'regional')], max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('2024/2025', '2024/2025'), ('2023/2024', '2023/2024'), ('2022/2023', '2022/2023')], max_length=20, unique=True)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionInSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_in_seasons', to='competitions.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions_in_season', to='competitions.season')),
            ],
            options={
                'ordering': ['-season__name', 'competition__level', 'competition__name'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.competitionlevel'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact_person', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.city')),
                ('competition_in_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.competitioninseason')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.city')),
                ('competition_in_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.competitioninseason')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_away', to='competitions.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_home', to='competitions.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['date_time'],
            },
        ),
    ]
