# Generated by Django 5.1.1 on 2024-09-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitioninseason',
            options={'ordering': ['-season__name', 'competition__level', 'competition__name'], 'verbose_name_plural': 'Competitions in seasons'},
        ),
    ]
