# Generated by Django 5.1.1 on 2024-09-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='e_mail',
            new_name='email',
        ),
    ]
