# Generated by Django 5.1.1 on 2024-09-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_role', models.CharField(choices=[('1.R', '1.R'), ('2.R', '2.R'), ('1.L', '1.L'), ('1.L', '1.L')], max_length=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_referees', to='competitions.match')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='referees.referee')),
            ],
            options={
                'ordering': ['match__date_time'],
            },
        ),
    ]
