# Generated by Django 5.1.1 on 2024-09-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='referee_role',
            field=models.CharField(choices=[('1.R', '1.R'), ('2.R', '2.R'), ('1.L', '1.L'), ('2.L', '2.L')], max_length=5),
        ),
    ]
