# Generated by Django 5.1.1 on 2024-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0002_alter_delegation_referee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='referee_role',
            field=models.CharField(choices=[('1.R', '1st referee'), ('2.R', '2nd referee'), ('1.L', '1st line judge'), ('2.L', '2nd line judge')], max_length=3),
        ),
    ]
