# Generated by Django 5.1.1 on 2024-10-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_team_phone'),
        ('delegations', '0003_alter_delegation_referee_role'),
        ('referees', '0011_remove_refereelicencetype_competition_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delegation',
            unique_together={('match', 'referee')},
        ),
    ]
